### ISSUE TITLE
daily errors from different adapters regarding logrotate symlink

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.js-controller#607] opened 2020-01-12 12:05 UTC
`2020-01-11 06:45:06.091  - [31merror[39m: ical.0 (30581) uncaught exception: EEXIST: file already exists, symlink 'iobroker.2020-01-11.log' -> '/opt/iobroker/log/iobroker.current.log'
2020-01-11 06:45:06.104  - [31merror[39m: ical.0 (30581) Error: EEXIST: file already exists, symlink 'iobroker.2020-01-11.log' -> '/opt/iobroker/log/iobroker.current.log'
    at Object.symlinkSync (fs.js:909:3)
    at createCurrentSymLink (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:303:16)
    at EventEmitter.<anonymous> (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:530:17)
    at EventEmitter.emit (events.js:203:15)
    at /opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:607:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
2020-01-11 06:45:07.114  - [33mwarn[39m: ical.0 (30581) Terminated (UNCAUGHT_EXCEPTION): Without reason
2020-01-11 06:45:07.784  - [31merror[39m: host.BT3-PRO instance system.adapter.ical.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

2020-01-12 00:05:05.876  - [31merror[39m: host.BT3-PRO Caught by controller[0]: fs.js:114
2020-01-12 00:05:05.877  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     throw err;
2020-01-12 00:05:05.880  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     ^
2020-01-12 00:05:05.881  - [31merror[39m: host.BT3-PRO Caught by controller[0]: Error: EEXIST: file already exists, symlink 'iobroker.2020-01-12.log' -> '/opt/iobroker/log/iobroker.current.log'
2020-01-12 00:05:05.881  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at Object.symlinkSync (fs.js:909:3)
2020-01-12 00:05:05.881  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at createCurrentSymLink (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:303:16)
2020-01-12 00:05:05.881  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at EventEmitter.<anonymous> (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:530:17)
2020-01-12 00:05:05.882  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at EventEmitter.emit (events.js:198:13)
2020-01-12 00:05:05.882  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at Object.FileStreamRotator.getStream (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:609:16)
2020-01-12 00:05:05.882  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at new DailyRotateFile (/opt/iobroker/node_modules/winston-daily-rotate-file/daily-rotate-file.js:80:57)
2020-01-12 00:05:05.882  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at Object.keys.forEach.f (/opt/iobroker/node_modules/iobroker.js-controller/lib/logger.js:156:34)
2020-01-12 00:05:05.882  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at Array.forEach (<anonymous>)
2020-01-12 00:05:05.882  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at logger (/opt/iobroker/node_modules/iobroker.js-controller/lib/logger.js:105:48)
2020-01-12 00:05:05.883  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:181:42)

2020-01-12 12:50:05.687  - [31merror[39m: mihome.0 (3267) uncaught exception: EEXIST: file already exists, symlink 'iobroker.2020-01-12.log' -> '/opt/iobroker/log/iobroker.current.log'
2020-01-12 12:50:05.695  - [31merror[39m: mihome.0 (3267) Error: EEXIST: file already exists, symlink 'iobroker.2020-01-12.log' -> '/opt/iobroker/log/iobroker.current.log'
    at Object.symlinkSync (fs.js:909:3)
    at createCurrentSymLink (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:303:16)
    at EventEmitter.<anonymous> (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:530:17)
    at EventEmitter.emit (events.js:203:15)
    at /opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:607:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
2020-01-12 12:50:06.703  - [33mwarn[39m: mihome.0 (3267) Terminated (UNCAUGHT_EXCEPTION): Without reason
2020-01-12 12:50:07.793  - [31merror[39m: host.BT3-PRO Caught by controller[0]: { Error: EEXIST: file already exists, symlink 'iobroker.2020-01-12.log' -> '/opt/iobroker/log/iobroker.current.log'
2020-01-12 12:50:07.794  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at Object.symlinkSync (fs.js:909:3)
2020-01-12 12:50:07.794  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at createCurrentSymLink (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:303:16)
2020-01-12 12:50:07.794  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at EventEmitter.<anonymous> (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:530:17)
2020-01-12 12:50:07.795  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at EventEmitter.emit (events.js:203:15)
2020-01-12 12:50:07.795  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at /opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:607:20
2020-01-12 12:50:07.797  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:61:11)
2020-01-12 12:50:07.797  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
2020-01-12 12:50:07.798  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at startup (internal/bootstrap/node.js:283:19)
2020-01-12 12:50:07.798  - [31merror[39m: host.BT3-PRO Caught by controller[0]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
2020-01-12 12:50:07.798  - [31merror[39m: host.BT3-PRO Caught by controller[0]:   errno: -17,
2020-01-12 12:50:07.798  - [31merror[39m: host.BT3-PRO Caught by controller[0]:   syscall: 'symlink',
2020-01-12 12:50:07.798  - [31merror[39m: host.BT3-PRO Caught by controller[0]:   code: 'EEXIST',
2020-01-12 12:50:07.798  - [31merror[39m: host.BT3-PRO Caught by controller[0]:   path: 'iobroker.2020-01-12.log',
2020-01-12 12:50:07.799  - [31merror[39m: host.BT3-PRO Caught by controller[0]:   dest: '/opt/iobroker/log/iobroker.current.log' }`

**Comment by Apollon77** [comment] 2020-01-12 16:40
Which js-Controller?

**Comment by Diginix** [comment] 2020-01-12 18:31
JS-Controller 2.2.7
admin 3.7.7
nodejs 10.18.1
npm 6.9.0

**Comment by Apollon77** [comment] 2020-01-12 18:42
Do the adapters crash then once a day?!

**Comment by Diginix** [comment] 2020-01-12 19:17
No, at least not noticeable. ical adapter for example only runs only some seconds every 15 minutes.
I have no disruptive influences by this error. Just noticed it in a so far very clean log. My log level for JS-Controller is "warn".

**Comment by GermanBluefox** [comment] 2020-01-16 20:59
I could not find any problems: https://github.com/rogerc/file-stream-rotator/blob/master/FileStreamRotator.js#L303

**Comment by Apollon77** [comment] 2020-01-16 22:43
The problem is that we run multiple logger instances in parallel because each adapter has its own, so we have "concurrency". depending on their exact "first writes after 0:0:0" it can be that one deleted the symlink and before recreating an other recreates. basically in https://github.com/rogerc/file-stream-rotator/blob/master/FileStreamRotator.js#L303 thre is no additional try/catch.

I will provide an PR to them to add another try catch and maybe add verification of symlink target or such

**Comment by Apollon77** [comment] 2020-01-16 22:57
Reason is https://github.com/rogerc/file-stream-rotator/issues/65 ... Easy solution is just an additional try/catch ... we will see ... but in fact bug in library :-(

**Comment by Apollon77** [comment] 2020-01-17 23:30
Sub dep is fixed ... Now we hope that winston-daily-rotate-file catches up fast too https://github.com/winstonjs/winston-daily-rotate-file/issues/265

**Comment by Apollon77** [comment] 2020-01-24 08:13
fixed in 2.2.8

**Closed by Apollon77** 2020-01-24 08:13 UTC
Labels: dependency-error
