### ISSUE TITLE
js-controller 3.3 Adapter comaptibility

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1301] opened 2021-04-30 08:12 UTC
With js-controller 3.2 and js-controller 3.3 some additional checks were added to make sure that created objects match to the specifications and also written state values match to the object definition.

If something is not correct this is logged as "warning" log.

Please take the time to verify your adapter by ideally starting with a fresh instance and do some actions and verify the log. If you see a warn log there from these checks please adjust the adapter and fix the relevant cases.

This thread is for tracking purposes and allows questions and discussions

**Comment by HGlab01** [comment] 2021-04-30 14:19
I think the log-message is missleading, e.g.
`.serialNo" has wrong type "string" but has to be "number"`
This state is currently defined as number, so the message should be
`has wrong type "number" but has to be "string"`
isn't it?

**Comment by Apollon77** [comment] 2021-04-30 15:26
read full message :)

State value to set for "${id}" has wrong type "${typeof state.val}" but has to be "${obj.common.type}"

"State value to set" means the value that someone wants to write

**Comment by phifogg** [comment] 2021-05-01 11:14
I am with HGlab01 on this.. my first interpretation was my states are wrongly defined. But it seems my adapter is setting wrong values rather. This could be more explicit.

**Comment by Apollon77** [comment] 2021-05-01 11:41
Ok then please propse a better log message :-) In my eyes when reading the full message it should be clear :-)

**Comment by jpgorganizer** [comment] 2021-05-05 20:23
> With js-controller 3.2 and js-controller 3.3 some additional checks were added

do you have a list of that changes? which have been in 3.2 and which in 3.3.?

I cannot  see the message `State value to set for "xxx" has to be type "string" but received type "number"` with js-controller  3.2, but I've seen it in another log, but don't know which js-c version is running there.

How can I update to js-c  v3.3? I've v 3.2.16 installed and this seems to be the actual version.
Sorry, even I'm an adapter developer, I'm not very familiar with core ioBroker things :-)

**Comment by Apollon77** [comment] 2021-05-05 21:17
The changelog should give you all infos ;-)) Especially check the Developer sections https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md

"State value to set ..." error are new in js.controller 3.3.

js-controller 3.3 instructions and test thread in forum https://forum.iobroker.net/topic/44624/js-controller-3-3-jetzt-im-latest

What you mean with "Time schedule"? We work in an agile way and use GitHub projects where plans can be seen as tickets, also the upcomig 3.4 is listed there ... but from time to time we add new stuff, so monitoring js.contrller PRs is the best way to go if you want to know what will come i advance

**Comment by phifogg** [comment] 2021-05-06 07:24
> Ok then please propse a better log message :-) In my eyes when reading the full message it should be clear :-)

The issue you are trying to solve for is lazy programmers (like me) relying on javascripts automatic type cast. I would assume that most folks have set the state properties correctly but don't care when setting values. 

Reading it again a few times your message does make sense %/ Maybe make it a bit more explicit:

State value to set for "${id}" has wrong type "${typeof state.val}" but state is defined to be "${obj.common.type}"

Or

Setting state value for "${id}" called with wrong type "${typeof state.val}", expected "${obj.common.type}"

**Comment by Apollon77** [comment] 2021-05-06 21:42
We adjusted in js.controller 3.3.8 alreayd when I remember correctly ...

**Comment by anwa** [comment] 2021-05-07 08:30
I already made PR for tankerkoenig, unifi and weatherunderground. But there are so many :(
Unfortunately not all adapters are well supported by there authors. And sometimes the Problem is more complex like in sonoff or unifi.
For example unifi: The API responds some number values as string??? So we have to check and convert the values back to numbers...

**Comment by Apollon77** [comment] 2021-05-07 09:22
Thank you for our support here and yes some are easy, some requires deeper checks.
We can only work on them one after the other :-(

Any PR is highly appreciated!

**Comment by foxriver76** [comment] 2022-09-03 00:12
Can we close this issue now? ;-)

**Closed** 2022-12-27 23:44 UTC
Labels: tracking :eye:
