### ISSUE TITLE
[bug]: Wrong estimation of RAM on MacOS

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#2643] opened 2024-03-19 05:31 UTC
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

If ioBroker runs on MacOS it constantly brings an error about a leak of RAM. We should disable this estimation to avoid this warning

**Comment by foxriver76** [comment] 2024-03-19 06:50
Duplicate of #1838

**Closed by foxriver76** 2024-03-19 06:50 UTC
Labels: bug :lady_beetle:
