### ISSUE TITLE
[Feature request] Provide convenience methods for adapters for infrastructure-related tasks

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#202] opened 2018-05-25 09:05 UTC
Some things adapters need to do are unnecessarily complicated. This includes
1. updating their own configuration from code: 
    1. Read `system.adapter.${adapter.namespace}` object
    2. modify the configuration
    3. write the object back
2. Restarting themselves. This can be done in 2 ways:
    1. `process.exit(<code>)`
    2. storing the adapter configuration without changing it (see 1.)
3. Installing additional npm libraries. The js-controller has methods for it, but if adapters need to do it too, they usually ship their own `npmInstall` method, like ioBroker.javascript does. Whenever npm decides to change things up (like npm 5+), those methods need to be updated in js-controller and all adapters.

I propose we move all the infrastructure-related stuff into the js-controller (if not already in there) and expose it to the adapters, either via a method on the adapter class, or with a method exposed by `util.js`.

Proposed methods:
- [x] `Adapter.restart()`: Restarts the adapter (maybe with an optional reason that appears in the log) (#208)
- [x] `Adapter.updateConfig(config)`: Updates the adapter config. `config` is a subset of the config object that will be merged with the existing config object. (#208)
- [ ] `installNpmModules(modules, location)`: Installs additional npm modules (string array or single string) in the given location and "--save"s them in the package.json there. The optional `location` argument would be `"adapter"` (default) for the current adapter folder or `"iobroker"` for the root iobroker folder.
- [ ] `uninstallNpmModules(modules, location)`: Uninstalls npm modules (the opposite of `installNpmModules`). Adapters should probably not be allowed to uninstall modules from the root ioBroker folder.

**Comment by GermanBluefox** [comment] 2018-05-25 10:42
I must say, I do not see the need for that.
Read config is done by start and stored in adapter.config

Why the adapter must update its own config?

If you need to install npm module it is too late.

What we need is checking/installing of Linux packages. But during the
installation.

25 мая 2018 г. 11:05 пользователь "AlCalzone" <notifications@github.com>
написал:

Some things adapters need to do are unnecessarily complicated. This includes

   1. updating their own configuration from code:
   2. Read system.adapter.${adapter.namespace} object
   3. modify the configuration
   4. write the object back
   5. Restarting themselves. This can be done in 2 ways:
   6. process.exit(<code>)
   7. storing the adapter configuration without changing it (see 1.)
   8. Installing additional npm libraries. The js-controller has methods
   for it, but if adapters need to do it too, they usually ship their own
   npmInstall method, like ioBroker.javascript does. Whenever npm decides
   to change things up (like npm 5+), those methods need to be updated in
   js-controller and all adapters.

I propose we move all the infrastructure-related stuff into the
js-controller (if not already in there) and expose it to the adapters,
either via a method on the adapter class, or with a method exposed by
util.js.

Proposed methods:

   - Adapter.restart(): Restarts the adapter (maybe with an optional reason
   that appears in the log)
   - Adapter.updateConfig(config): Updates the adapter config. config is a
   subset of the config object that will be merged with the existing config
   object.
   - installNpmModules(modules, location): Installs additional npm modules
   (string array or single string) in the given location and "--save"s them in
   the package.json there. The optional location argument would be "adapter"
   (default) for the current adapter folder or "iobroker" for the root
   iobroker folder.
   - uninstallNpmModules(modules, location): Uninstalls npm modules (the
   opposite of installNpmModules). Adapters should probably not be allowed
   to uninstall modules from the root ioBroker folder.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ioBroker/ioBroker.js-controller/issues/202>, or mute
the thread

**Comment by GermanBluefox** [comment] 2018-05-25 10:44
Adapter restart is strange too. If adapter has type schedule, you can stop
the adapter with adapter.stop

пт, 25 мая 2018 г., 12:43 Smart Home - ioBroker <dogafox@googlemail.com>:

**Comment by AlCalzone** [comment] 2018-05-25 11:26
Let me give you a few examples:

> Read config is done by start and stored in adapter.config Why the adapter must update its own config? 

Tradfri uses the configured security code to authenticate with the gateway. As a result it receives a username and authentication code which must be used for future communication as IKEA forbids to permanently store the security code. Those are now stored in the adapter config and the security code is erased:
https://github.com/AlCalzone/ioBroker.tradfri/blob/master/src/main.ts#L108

> If you need to install npm module it is too late. 

https://github.com/ioBroker/ioBroker.javascript/blob/master/main.js#L610
The JS adapter automatically installs user-defined npm modules. I don't see why there shouldn't be another adapter that does a similar thing

> Adapter restart is strange too.

https://github.com/ioBroker/ioBroker.javascript/blob/master/main.js#L156
https://github.com/ioBroker/ioBroker.javascript/blob/master/main.js#L189
Again, the JS adapter automatically restarts when global scripts are enabled/disabled.

Or just for disabling the adapter:
https://github.com/ioBroker/ioBroker.js-controller/issues/197#issuecomment-388949065

I think it is much easier to understand (especially for new developers) if there are just some methods `adapter.stop()` or `adapter.disable()` or `adapter.restart()` instead of some crypting reading and storing of foreign objects.

> What we need is checking/installing of Linux packages. But during the installation.

While I agree, this goes in a different direction than I intend here.

**Comment by AlCalzone** [comment] 2018-05-25 11:30
And just to be clear: **I'm willing to help with that work**, I just want to check if you're interested in having such functionality.

**Comment by Apollon77** [comment] 2018-05-25 20:43
I also thought a bit about the ideas. 

Updating own config is a good idea in my eyes. We had questions in Forum about that and we also have such “one time sync” topics that like hm-rpc are done using config. In fact it is only a wrapper around getObject-extendobject but a bit easier. 

Restarting adapter is normally too easy, but if we some time want to differentiate between a error/crash with restart, a “planned” restart or an stop-and-disable methods for this make sense that we can then use and change and all Adapters that use them get new logic with an js-Controller update. Adapter.stop already exists, maybe enhancing this with a parameter or such but also make sure stop call kills process if needed?
Disabling as own method or part of stop is also helpful. 
In the end this is for new adapter developers that they do not need much how things work internally. 

Npm install/uninstall i really see as a more special case. Scripting Adapter like JavaScript and node-red we using this. For others it is more used in “post-install” or?! On the other side to provide a controllable way that we can change centrally it could make sense. Especially because ioBroker encapsulates all the npm stuff for users and devs. I would see this more in utils.js calling js-controller functions or such to prevent duplicate code ...

**Comment by AlCalzone** [comment] 2018-05-26 13:54
> In the end this is for new adapter developers that they do not need much how things work internally
> [...]
> On the other side to provide a controllable way that we can change centrally it could make sense. Especially because ioBroker encapsulates all the npm stuff for users and devs.

Exactly my points!

> I would see this more in utils.js calling js-controller functions or such to prevent duplicate code ...

In the `utils.js` we include in every adapter, we already expose the `Adapter` class. Maybe add another namespace `system` (or something like this), so devs can just write:
```js
const utils = require(...);
utils.system.npmInstall(...);
```
Putting it into a namespace would allow to add new methods without having to change `utils.js` every time.

**Comment by GermanBluefox** [comment] 2018-05-26 14:17
Not utils. It must be js-controller/lib/tools

Utils is only to find the controller. Nothing more

сб, 26 мая 2018 г., 15:54 AlCalzone <notifications@github.com>:

**Comment by AlCalzone** [comment] 2018-05-26 15:16
> Utils is only to find the controller. Nothing more

I think you misunderstood what I meant. Just like you wrote, the methods themselves should be in the js-controller, for example in `lib/tools`. I was thinking about how we expose them to adapters. `utils.js` currently exposes these properties:
```js
// ...
const Adapter = require(path.join(controllerDir, 'lib/adapter.js'));

module.exports = {
    controllerDir,
    getConfig,
    Adapter,
    appName
};
```

I would add another property to the exports, which contains a couple of methods from `js-controller/lib/tools`, but not all of them. For example:
```js
// js-controller/lib/tools:
// ...
const adapterTools = {
    npmInstall,
    // and other methods we want to expose to adapters
};
module.exports = {
    // all current exports, plus
    adapterTools
};
```
This way the controller can control which methods are exposed to adapters. And in the adapter utils:
```js
// ...
const Adapter = require(path.join(controllerDir, 'lib/adapter.js'));
const adapterTools = require(path.join(controllerDir, 'lib/tools.js')).adapterTools;

module.exports = {
    controllerDir,
    getConfig,
    Adapter,
    system: adapterTools,
    appName
};
```

How does that sound?

**Comment by GermanBluefox** [comment] 2018-06-05 13:11
1. Adapter.restart() => ok,
2. Adapter.updateConfig(config) => ok,
3. un/installNpmModules(modules, location) => ok, but in tools.js (direct, because can be used by controller too)

**Comment by Apollon77** [comment] 2020-04-09 06:32
I would like to plan the "Npm stuff" fpr controller 3.1 and also then very fast adjust the adapters. Currently the problem is that multiple npm processes could run in parallel in these cases ... ok hopefully the adapter stuff is running "in the local adapter node_modules" but to be sure we should queue all npm actions in the host process

**Comment by AlCalzone** [comment] 2020-04-09 12:52
> hopefully the adapter stuff is running "in the local adapter node_modules"

You cannot be sure of that. npm deduplicates dependencies in the parent folder. So queueing all processes in the controller only makes sense.

**Comment by Apollon77** [comment] 2020-04-09 16:09
Thats why I planned it for 3.1

**Comment by AlCalzone** [comment] 2020-04-24 06:58
The linked PR adds new methods for async execution of child processes. We should leverage them in the new npm installation routines. There are already some dedicated methods in place but they could be improved this way.

**Comment by Apollon77** [comment] 2020-12-29 14:48
Move to 3.3 for completion? @AlCalzone

**Comment by foxriver76** [comment] 2021-12-20 09:10
we just need to expose install/uninstall which is defined in tools js. I would propose to expose it via adapter-core.

**Comment by foxriver76** [comment] 2022-01-06 16:28
Edt: we have https://github.com/ioBroker/ioBroker.js-controller/blob/d0505f94e1d4b1bc8c642d7ef41c2342aa2052e6/packages/adapter/lib/adapter/adapter.js#L204 thus whole tools is exposed

**Closed by foxriver76** 2022-01-06 16:28 UTC
Labels: enhancement, adapter related

**Comment by AlCalzone** [comment] 2022-01-06 17:49
I'm not sure if I would "officially" expose everything though

**Comment by foxriver76** [comment] 2022-01-06 18:30
Then we have to feel if we can remove it because I don’t know how long it is in ;-)

**Comment by Apollon77** [comment] 2022-01-07 13:48
* cameras
* pimatic
* pushover
* admin
* cloud
using it

**Comment by foxriver76** [comment] 2022-01-09 19:38
> encrypt/decrypt

we have this on adapter level too

**Comment by foxriver76** [comment] 2022-01-09 19:41
> * migrateEncodedAttributes

this does not exist in tools
