### ISSUE TITLE
Dependency-Check im Multihost- Betrieb: required adapter "admin" not found!

### ISSUE THREAD

**Issue by Basti131b** [ioBroker/ioBroker.js-controller#325] opened 2019-02-01 18:08 UTC
Leider habe ich ein paar Probleme mit Adaptern, die den Error:

startInstance system.adapter.statistics.0: required adapter "admin" not found!

ausgeben.

Es betrifft die Adapter Statistics und sourceanalytix

Auch der Adapter Icons- Ultimate liefert einen ähnlichen Fehler:

startInstance system.adapter.icons-ultimate-png.0: required adapter "web" not found!

Vorübergehender Workaround hierfür:

eine separate Instanz des Adapters admin bzw. web auf demselben Host installieren wie die betreffende Instanz mit dem Fehler und anschließend deaktivieren.

**Comment by Apollon77** [comment] 2019-02-01 21:50
Adapter dependecies should be check on generla level instead of host level

**Comment by AlCalzone** [comment] 2019-03-03 13:11
BLE and Tradfri are also affected by this bug.

**Comment by AlCalzone** [comment] 2019-03-03 13:32
On a first glance, the code only checks which "processes" are active on the current host, instead of looking at the objects DB.

**Comment by nob0dy80** [comment] 2019-03-04 09:15
this issue is open over a month now.. will this be fixed ?!?!

**Comment by AlCalzone** [comment] 2019-03-04 10:32
Wanna give it a shot? If not, have some patience!

**Comment by nob0dy80** [comment] 2019-03-12 22:29
@AlCalzone 
Yeah sure, tell me when you got time teaching me programming :-)

**Comment by cburghardt** [comment] 2019-05-14 16:24
Maybe something along those lines in controller:checkVersion

Replace
`        for (let p in procs) {
            if (!procs.hasOwnProperty(p)) continue;
            if (procs[p] && procs[p].config && procs[p].config.common && procs[p].config.common.name === name) {
                if (version && !semver.satisfies(procs[p].config.common.version, version)) {
                    logger.error('host.' + hostname + ' startInstance ' + id + ': required adapter "' + name + '" has wrong version. Installed "' + procs[p].config.common.version + '", required "' + version + '"!');
                    return false;
                }
                isFound = true;
            }
        }`
with
`                    objects.getObjectList({startkey: 'system.adapter.', endkey: 'system.adapter.\u9999'}, (err, objs) => {
                        for (let i = 0; i < objs.rows.length; i++) {
                            if (objs.rows[i].value.type !== 'adapter') continue;
                            if (name === objs.rows[i].value.common.name) {
                                if (version && !semver.satisfies(objs.rows[i].value.common.version, version)) {
                                    logger.error('host.' + hostname + ' startInstance ' + id + ': required adapter "' + name + '" has wrong version. Installed "' + objs.rows[i].value.common.version + '", required "' + version + '"!');
                                    return false;
                                }
                                isFound = true;
                            }
                        }
                    });`

**Comment by cburghardt** [comment] 2019-06-04 17:33
@AlCalzone do you need a pull request?

**Comment by AlCalzone** [comment] 2019-06-05 05:13
@germanbluefox what about this proposed change?

**Comment by Apollon77** [comment] 2019-06-05 07:01
i would see that as a solution - better then removing deps ... so yes a PR would be awesome

**Comment by GermanBluefox** [comment] 2019-06-05 07:40
The Problem is, that dependencies were targeted not for version matching, but for "these adapters are required for functioning", e.g vis **cannot** run without web.

In this case, ble can run without admin, it is only nice to have the specific version of admin if it is there.

**Comment by Apollon77** [comment] 2019-06-05 07:53
No, ble do not have a admin-v2 config page (index.htmlö) so in fact can not be configured, so mot run with an Admin1 or 2.
And the second topic is that the current logic reqired the dependent adapter to be on the same host as the one to newly install and this makes problem because this is unneeded. The dependent adapter just needs to be "there somewhere"

**Comment by AlCalzone** [comment] 2019-06-05 08:34
> ble do not have a admin-v2 config page (index.html) so in fact can not be configured, so not run with an Admin1 or 2.

The same is true for all new adapters created with the adapter creator

**Comment by cburghardt** [comment] 2019-06-06 15:10
If I understand the design correctly it does not really make sense to verify if an adapter is locally installed. This defeats the purpose in a multihost setup. And I can see this right now as I have 2 additional "dead" instances of admin lingering around just for the sake of a dependency check.

**Comment by AlCalzone** [comment] 2019-06-06 15:26
Ok so we decided as follows: This bug will be fixed, but we won't enforce having an admin instance installed at all.

**Comment by cburghardt** [comment] 2019-06-27 18:04
Will that be fixed in 1.5.x then?

**Comment by AlCalzone** [comment] 2019-06-28 07:24
Probably not - but the dependency will be removed from adapters so they work with 1.5.x

**Comment by cburghardt** [comment] 2019-07-12 17:49
Fixed for BLE at least

**Comment by Apollon77** [comment] 2019-08-31 22:35
Ok, in fact the todo would be to create a "new" dependency field. The current "dependency" means "dependecy-on-the-host-where-adapter-is-installed". So the name proposal would be "globalDependency" (because current one is "local".

We could add this into 2.0.0 ... @AlCalzone  @GermanBluefox

**Comment by Apollon77** [comment] 2019-08-31 22:51
Question to answer for a "global version check": If the same adapter is installed on different hosts with different versions ... which one to use for the dependency comparism? The highest or the lowest version?

**Comment by AlCalzone** [comment] 2019-09-01 18:12
We need to think about the use cases of this dependency. One is the admin instance where new adapters require **at least one** admin instance with **version >= 3**. So in this case the globally highest version would make sense.

**Comment by Apollon77** [comment] 2019-09-01 22:27
especially for admin it is much more problematic I think ... "the used one" (also all active ones?) needs to be >=3 ...

**Comment by cburghardt** [comment] 2019-09-02 07:14
Does it make sense to think about such complexity for a single adapter instead of enforcing the same version? In a multihost environment which is still manageable there should only be one admin for example.

**Comment by Apollon77** [comment] 2019-09-02 07:57
>  there should only be one admin for example.
But this would limit ... I, as an example, have two Admin instances. One without Auth for local usage only and one with Auth and SSL and such ...

**Comment by Apollon77** [comment] 2020-02-10 10:44
Topic is getting more and more important - especially for Adapters like Admin and Web

**Comment by foxriver76** [comment] 2020-04-03 10:00
Why can't we just design the check like, if not multihost, check like we do now.
If multiohost do the following: 
- if dep is js-controller check on installed host if satisfied 
- if dep is a normal adapter, check that at least one host satisfies the requirements and (following @Apollon77 approach) if more than one host has the dependency installed, check that version fits on all. 

I would only introduce a new io-pack field if really necessary, especially `globalDependencies` will be confusing for some adapter devs which are not into the multihost stuff (like me).

**Comment by AlCalzone** [comment] 2020-04-03 11:09
Sounds good. 
There might be the case that some adapter needs another on the same host, but I'm not sure if that is realistic.

**Comment by Apollon77** [comment] 2020-04-03 16:22
I fear it is not that easy. We have "required local dependencies", "system wide" and a special case :).

Examples for "required local dependencies":
* js-controller locally needs to have special minimum version for adapter to work
* proxy adapter needs to have a special web on same host because socket.io can be configured to run as "extention" in web (this means code needs to be on the same host).

Examples for "system wide":
* vis needs at least version x from web. Here all parts of vis are in the iobroker file store "uploaded" and so there is no real local dependency (@GermanBluefox I hope so, or?! All widgets are nmot read locally from vis, or?), but to display it correctly you need a certain web version

Special case:
* Some of those extension adapters (socket.io/geofency...) that can be configured "standalone" or to use a certain web instance to "plug in". So in order to have this working it needs to be required that they only show "the web instances on same host" in their admin when it is about "where they can plug in".

**Comment by Apollon77** [comment] 2020-04-04 21:56
Ok, I also checked that with @GermanBluefox and yes these are our cases.

The only backward compatible way I see is the way with the "dependenciesGlobal" or "globalDependencies" ...

**Comment by foxriver76** [comment] 2020-04-06 21:27
`common.globalDependencies` Would be my favorite. And let `common.dependencies` be local

**Comment by GermanBluefox** [comment] 2020-04-07 07:23
Ok. Global Dependencies sounds good

**Comment by Apollon77** [comment] 2020-04-07 12:45
docs are updated with next commit from me

**Closed** 2020-04-07 15:05 UTC
Labels: enhancement
