### ISSUE TITLE
Object import failed with  'replace' of null

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.js-controller#453] opened 2019-09-19 06:51 UTC
Trying to import
https://forum.iobroker.net/assets/uploads/files/1568851160314-deconz.0.sensors.44.open.json
fails with
(/usr/local/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1327:28)
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: TypeError: Cannot read property 'replace' of null
`

019-09-19 08:48:35.352 | error | instance system.adapter.admin.0 terminated with code 0 (OK)
-- | -- | --
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: at process._tickCallback (internal/process/next_tick.js:181:9)
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: at _combinedTickCallback (internal/process/next_tick.js:132:7)
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: at /usr/local/iobroker/node_modules/iobroker.admin/node_modules/socket.io/lib/socket.js:503:12
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: at Socket.emit (events.js:217:7)
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: at emitThree (events.js:136:13)
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: at Socket.<anonymous> (/usr/local/iobroker/node_modules/iobroker.admin/lib/socket.js:632:25)
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: at Adapter.setForeignObject (/usr/local/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1327:28)
Caught | 2019-09-19 08:48:35.352 | error | by controller[0]: TypeError: Cannot read property 'replace' of null

`

**Comment by Apollon77** [comment] 2019-09-19 08:22
which js-controller version?

**Comment by TA2k** [comment] 2019-09-19 08:25
the latest 1.5.14

**Comment by Apollon77** [comment] 2019-09-19 08:29
Can you please retest with 2.0?

**Comment by TA2k** [comment] 2019-09-19 08:37
same with 2.0.2 plus this repeating error:
Objects 127.0.0.1:59473 (Init=false) Redis error:Error: Invalid Chunk: parse failed

`

019-09-19 10:35:50.523 | error | Caught by controller[0]: TypeError: Cannot read property 'replace' of null
-- | -- | --
admin.0 | 2019-09-19 10:35:50.513 | info | terminating
admin.0 | 2019-09-19 10:35:50.511 | info | terminating http server on port 8081
admin.0 | 2019-09-19 10:35:50.510 | error | at process._tickCallback (internal/process/next_tick.js:181:9)
admin.0 | 2019-09-19 10:35:50.510 | error | at _combinedTickCallback (internal/process/next_tick.js:132:7)
admin.0 | 2019-09-19 10:35:50.510 | error | at /usr/local/iobroker/node_modules/iobroker.admin/node_modules/socket.io/lib/socket.js:503:12
admin.0 | 2019-09-19 10:35:50.510 | error | at Socket.emit (events.js:217:7)
admin.0 | 2019-09-19 10:35:50.510 | error | at emitThree (events.js:136:13)
admin.0 | 2019-09-19 10:35:50.510 | error | at Socket.<anonymous> (/usr/local/iobroker/node_modules/iobroker.admin/lib/socket.js:632:25)
admin.0 | 2019-09-19 10:35:50.510 | error | at Adapter.setForeignObject (/usr/local/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1797:28)
admin.0 | 2019-09-19 10:35:50.510 | error | TypeError: Cannot read property 'replace' of null
admin.0 | 2019-09-19 10:35:50.510 | error | uncaught exception: Cannot read property 'replace' of null
host.| 2019-09-19 10:35:47.890 | error | Objects 127.0.0.1:59473 (Init=false) Redis error:Error: Invalid Chunk: parse failed

`

**Comment by Apollon77** [comment] 2019-09-19 08:45
Ok, I will try to reproduce in 2.0 and fix there

**Comment by Apollon77** [comment] 2019-09-19 12:18
Ok, seems to be more an admin issue ... the setForeignObject method is called with "undefined" as id in first parameter. But because of https://github.com/ioBroker/ioBroker.admin/blob/master/lib/socket.js#L630 it is more the admin frontend code that does this wrong call.
I will fix that the adapter dies in this case, but please open an admin issue to fixit there too.

**Comment by Apollon77** [comment] 2019-09-19 12:48
fixed in js-controller 2.0.3

**Closed by Apollon77** 2019-09-19 12:48 UTC
Labels: bug

**Comment by Apollon77** [comment] 2019-09-19 21:20
@TA2k Details for the admin issue. Reason in Code is:
https://github.com/ioBroker/ioBroker.admin/blob/master/src/js/adminObjects.js#L847 ... if only one oebject is in the file then currently it is expected to be a full object, only multiple objects are a "object" ... This could be fixed in admin I think ...
