### ISSUE TITLE
[Enhancement] Make instance start order configurable

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.js-controller#1054] opened 2020-10-06 07:52 UTC
Current situation : 

Admin adapter ist startet first, then all others in order which they have been added to the system

Wanted situation : 
Capability to have a priority list defined which adapters should start first (all other can be as is, lets not overload configuration)

Use case : several adapters and scripts are created to monitor system processes or act on changes/updates.
In several situation adapter they should handle the event of are starter earlier then the adapter itself, in a result of that unneeded error's occur of information is missing.

Practice Example : Seq adapter which is sending all logging information to a centralized environment. Its no starting almost at the end and by that I miss or logging of ioBroker start

**Comment by foxriver76** [comment] 2020-10-06 09:56
Duplicate of https://github.com/ioBroker/ioBroker.js-controller/issues/279

**Closed by foxriver76** 2020-10-06 09:56 UTC
