### ISSUE TITLE
Compact-Mode: Adaptercheck Tracking

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#512] opened 2019-10-20 22:03 UTC
In order to prepare the stable release of js-controller 2.0 and to prevent users having problems with compact mode usage of adapters we want to make sure adapters are really working in compact mode when it is available.

Details about compact mode and how to use it  can be taken from https://github.com/ioBroker/ioBroker.js-controller/blob/master/README.md#start-adapter-instances-in-compact-mode

All developers should please use the latest js-controller 2.0 version and check their adapters in compact mode.
Beside the normal functionality please especially test stopping the adapter and starting it again. 

After stopping make sure that no state updates happen anymore. Please check your code and make sure that in "on unload" really ALL Timeouts and Intervals are stopped correctly and all used Connections (Network, Serial, Sockets ...) are also closed. Ideally make sure to call the callback when this has finished or check how long all this closing needs (e.g. socket.io closing sometimes needs 1s). By default the adapter is stopped 500ms after calling onUnload independent if callback was already called or not. You can increase that time if needed by setting common.stopTimeout in io-package with an higher value (in ms).

Please also check that multiple instances of your adapter in the same compact group works and that the instances are not mising up somehow.

Please support us to create the best experience for all our users when they want to use the compact mode.
Thank you!

**Comment by Zefau** [comment] 2019-10-21 19:15
nuki-extended adapter fails with error
```
startInstance system.adapter.nuki-extended.0: required adapter "web" not found!
```

`io-package.json` defines it as dependency:
```
        "dependencies": [
            {
                "web": ">=1.7.1"
            }
        ],
```

I have version `v2.4.6` installed.

**Comment by forelleblau** [comment] 2019-10-21 19:16
solalog-Adapter:
Gemäss Log werden die 'on.unload' Befehle nicht ausgeführt:
`adapter.on('unload', function(callback) {
    try {
      clearInterval(polling);
      adapter.log.info('[END] Stopping solarlog adapter...');
      adapter.setState('info.connection', false, true);
      callback();
    } catch (e) {
      callback();
    }
  });`

![image](https://user-images.githubusercontent.com/44144152/67235515-856ed780-f447-11e9-9857-f1707b54fead.png)

Wie kann das korrigiert werden?

**Comment by Apollon77** [comment] 2019-10-21 19:28
@Zefau Can it be multihost and on the host hwhere you want to install hue-extended no web instance is localed? This has nothing to do with Compact mode.

**Comment by Zefau** [comment] 2019-10-21 19:29
I'm not running a multihost.

**Comment by Apollon77** [comment] 2019-10-21 19:31
@forelleblau In "unload" it needs to be checked that adapter and also adapter.log still exists ... becaus eit could be already gone when called. I think it runs into the catch because of something no longer existing.moste likely it is the "adapter.log". so maybe write 

```
adapter.log && adapter.log.info('[END] Stopping solarlog adapter...');
```

**Comment by forelleblau** [comment] 2019-10-21 20:02
@Apollon77  thanks, unfortunately this helps only in some (reason unknown) cases. Her two other log-versions beside the one above:

OK-looking:

![image](https://user-images.githubusercontent.com/44144152/67238932-4ee88b00-f44e-11e9-8c5b-d4e2a83ea18e.png)

also not-ok:

![image](https://user-images.githubusercontent.com/44144152/67238990-70e20d80-f44e-11e9-806d-2d8e36ec3dce.png)

**Comment by Apollon77** [comment] 2019-10-21 20:24
This only about "logging" and sometimes the logs do not come through that close to the end of the process.

**Comment by Apollon77** [comment] 2019-10-21 20:30
PS: Der nächste .35 vom Controller lässt den prozess etwas mehr zeit ... dann sollte mehr Logging durhckommen

**Comment by Apollon77** [comment] 2019-10-21 20:31
@Zefau Kannst DU bitte mal web auch im compact mode laufen lassen ... in der gleichen gruppe wie hue-extended. geht es dann?

**Comment by Zefau** [comment] 2019-10-21 20:36
Jo, das funktioniert.

**Comment by Apollon77** [comment] 2019-10-21 20:36
kk, fixe ich im controller. Bug gefunden :-)

**Comment by Apollon77** [comment] 2019-10-21 21:04
@Zefau Please install js.controller version from GitHub and try again with the "original setting" regarding web. Should now work as long as on same host

**Comment by Zefau** [comment] 2019-10-22 07:07
Confirmed working
```
root@bananapim3:~# iobroker compact web.0 status
Adapter supports compact mode:     true
Compact mode enabled for instance: true
Compact group:                     2
root@bananapim3:~# iobroker compact nuki-extended.0 status
Adapter supports compact mode:     true
Compact mode enabled for instance: true
Compact group:                     1
root@bananapim3:~# iobroker compact status
Compact mode for this host is currently enabled
```

**Comment by Apollon77** [comment] 2019-10-22 07:09
Thank you!

**Comment by forelleblau** [comment] 2019-10-22 20:03
@Apollon77 : .35 installiert, Log nun ok. Funktioniert alles. Danke

**Comment by angelnu** [comment] 2019-10-23 07:19
I have tested that compact works on Linux but I think something is wrong on Windows. I thought it was my adapter (Chromecast) so I tested with sonoff which was updated by @GermanBluefox a couple of days ago:
![image](https://user-images.githubusercontent.com/4406403/67367468-d67ce980-f575-11e9-8510-47f8d42290eb.png)

Versions (takenyesterday  from Gihub master):
- controller: 2.0.35
- sonoff: 2.3.0

**Comment by Apollon77** [comment] 2019-10-23 08:21
WTF all slashes are missing? aaaahhhh ... interesting ... Please install js-controller from GitHub, I changed one place .. working now?

**Comment by angelnu** [comment] 2019-10-23 08:42
Compact wotks now in Windows @Apollon77 :)

**Comment by angelnu** [comment] 2019-10-23 09:21
But I think there is a race condition in case there are multiple listeners for "unload". I have multiple listerners (one for each adapter) so each register for the event in order to close its connections. They all get the event (good) but then the adapter logs "terminated" after the first unload event calls the callback:
![image](https://user-images.githubusercontent.com/4406403/67378164-21ebc380-f587-11e9-815c-fa0a8b1b8acb.png)

I would expect the adapter to terminate only after all the event callbacks have been received or by force after 500 ms.

**Comment by Apollon77** [comment] 2019-10-23 09:39
@angelnu Hm. multiple listeners that all call the callback is kind of very unexpected behaviour and currently (also also in the past) not really handled. The expectation is that there is one callback (as usually with callbacks!). We could use "once" there, but then you would get exceptions.

I have adjusted now that all callbacks after the first one are ignored (it's on GitHub), but please know that this means that the first callback triggers the real process "stopping" and latest 500ms after this irst callback everything is gone, especially the DB connections and such.

So in fact : better handle that in your code that you call the unload callback after ALL your internal stuff has executed and make sure to have high enought stopTimeout set in iopackage

**Comment by angelnu** [comment] 2019-10-23 09:53
Ok, I can implement that a central adapter destroyer calls the mutiple destroyers before calling the callback. I will do that.

**Comment by mcm1957** [comment] 2024-04-01 18:07
@Apollon77 
Is there anything to do based on this issue?
Looks like it is outdated.

**Closed** 2024-04-02 09:32 UTC
Labels: tracking :eye:, compact mode :baby:
