### ISSUE TITLE
changes in object settings clears already made material.ui settings

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.js-controller#544] opened 2019-12-05 18:50 UTC
Bug besteht schon seit JS-Controller 1.x. und war meines Wissens noch nie gefixt.
Mehr hier:
https://github.com/ioBroker/ioBroker.history/issues/45

preserveSettings funktioniert für den Part custom > material eines Objektes nicht.
Sobald man z.B. history Einstellungen ändert, geht der _material_ Teil innerhalb von custom verloren
`"custom": {
"material": {
"admin": {
"name": "Test",
"colorOn": "",
"doubleSize": "",
"icon": "",
"background": "",
"enabled": true
}
}
}`

**Comment by Apollon77** [comment] 2019-12-05 22:06
Hm ... I tried to reproduce it ... for me it stays 
DO you have a complete object json please with material where it happens reproducable?

**Comment by Diginix** [comment] 2019-12-06 07:52
You can see a sample object before and after here:
https://forum.iobroker.net/post/335616

**Comment by Apollon77** [comment] 2019-12-06 14:28
So The reason is that material is in "common.custom.material" ... with the settings from the material adapter I would have expected it in common.material ...

And in the end the reason is that "preserveSettings" currently only works on the "common" level. So common.custom is set on "custom change" completely depending on which custom-pages are available ... and because material do not have a custom-settings-page it is never in thzere and so settings gets lost.

The logic in general for this is https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/objects/objectsInMemFileDB.js#L1694( and a "duplicate" in the objects lib).

So options/questions in my eyes:
1.) Is material adapter really storing on a wrong place? That would be bad and should be fixed (and hopefully he can migrate the data)
2.) Makes it sense that custom is always stored complete. Or shpuld we not build in a special "deep merge" for this too to allow updates for just one "custom-key"? If we are lucky a node.extend "non-deep merge" for "common.custom" should work directly

@GermanBluefox

**Comment by Diginix** [comment] 2019-12-07 11:18
Why is common > custom >material wrong?
Adapter settings from statistics or history are on this place as well. What is the difference between material and history or statistics that it should be one level above?

https://www.dropbox.com/s/bhpgwrj2ftpb8tr/object_common.png?dl=0

**Comment by AlCalzone** [comment] 2019-12-07 12:24
How are these adapter-specific settings written to the objects? I would expect that extendObject is used and that the properties in `custom` are handled just like the properties on the root level, because we always go one level deeper than usual here.

**Comment by Apollon77** [comment] 2019-12-07 16:20
In fact (as soon as I understand it) ioBroker offers two different ways for store adapter/adapterinstance-specific data into an objects "common" part.

But because these data exist outside of everything that an adapter developer knows (because in this case their objects are enhanced by other mechanisms) there is special logic to preservce some data on "setObject" on existing objects. extendObject is irrelevant here because handled this already.

1.) An Adapter can define that he want to add an own "common"-level key to store adapterspecific dat. This is done by using "preserveSettings=material" as example. Currently the following keyspaces are used by adapters here: 'custom', 'smartName', 'material', 'habpanel', 'mobile'
When an adapter uses "setObject" to set an object which was not there before he would overwrite these keys because he do not know that someone else added them. So a special logic in the controller make sure that, if one of these keys are used, it will be preserved from the old object. But this mechanism is working fine here and not really the issue. Issue is in next point.

2.) If an adapter offers a "custom settings page" (those that are usually stored in common.custom and available under the wrench-symbol in admin ui) then the adapter tells in config "supportsCustom=true" and "preserveSettings=custom". The data that are entered on the "custom admin page" is then automatically stored in common.custom with the instance-name (e.g. "history.0" as key). When calling the custom page in admin by using the "wrench" the admin will collect all adapter that supports custom and allows to edit. Then when you save it admin makes sure to store ALL of these custom-instance-data in common.custom.
But because "setObject" is used there by admin there is no "deep" merge happening at the sub key level. And it also means that if material stores its data in custom, but do not provide a custom page admin will not know this key and so will not store the data, so it's missing/deleted.

Here we have the question if we not want to do a merge at least on the common.custom.* level ... but then "former installed adapters with custom data that now are uninstalled" will still have their data in the objects

**Comment by Apollon77** [comment] 2019-12-07 16:24
@AlCalzone Do not expect anything ;-) I think it still needs a bit time to introduce "extendObject" as best practice ... or maybe we really need https://github.com/ioBroker/ioBroker.js-controller/issues/492

**Comment by Diginix** [comment] 2020-01-06 17:02
Bug is still there with JS-Controller 2.2.7
admin 3.7.7
nodejs 10.18.0
npm 6.9.0

**Comment by Apollon77** [comment] 2020-01-06 17:35
Wwwwwwhhhaaaaatttt??? Should not be the case.

**Comment by Diginix** [comment] 2020-01-06 18:02
You know how to test it yourself. Just do it ;-)
Change history settings of an already configured object with active history and material settings and check it in raw before and after. The whole material {} block will be deleted.

**Comment by Apollon77** [comment] 2020-01-06 19:22
I was sure we tested it ... :-( we wil Check again.

**Comment by Apollon77** [comment] 2020-01-15 16:23
@Diginix And you also have installed Admin 3.7.7???

**Comment by Apollon77** [comment] 2020-01-16 21:59
Controller is great ... Admin is the reason: https://github.com/ioBroker/ioBroker.admin/issues/494

**Closed by Apollon77** 2020-01-16 21:59 UTC
