### ISSUE TITLE
iobroker start all will not stop

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.js-controller#548] opened 2019-12-06 23:05 UTC
The `iobroker start all` command is not terminated.
Neither the direct command nor `node iobroker.js start all` terminate the process. All adapters start though ...

**Comment by AlCalzone** [comment] 2019-12-07 09:48
I know what the problem is - will provide a PR tomorrow

**Comment by Apollon77** [comment] 2019-12-07 13:25
Fixed on github

**Closed** 2019-12-21 21:56 UTC
