### ISSUE TITLE
Check and decline adapterstarts and notify user via notification about blocklisted adapters

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2076] opened 2022-12-30 15:09 UTC
Enhance https://github.com/ioBroker/ioBroker.js-controller/pull/1960#issuecomment-1334449740 and also check in js-controller, prevent start of blocklisted versions as soon as received in repo!

**Comment by foxriver76** [comment] 2024-03-26 12:31
duplicate of #625

**Closed by foxriver76** 2024-03-26 12:31 UTC
Labels: enhancement :arrow_up:, controller related :volcano:
