### ISSUE TITLE
Can't disable storage of enabled objects (History Adapter)

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.js-controller#506] opened 2019-10-15 16:35 UTC
Disabling storage of enabled objects (for history adapter) is not possible in js-controller version 2.0.25 or 2.0.29. Saving of settings has no effect, objcet (storage) keeps enabled.

Raspi Pi4 system and Debian Buster VM testsystem
Both: NPM 6.9.0, NodeJs 10.16.3
Both: Admin 3.6.10, History Adapter 1.8.7

**Comment by Apollon77** [comment] 2019-10-16 05:27
I can not reproduce that :-( we had one such report in forum but only for iogo. 

I try to reproduce again.

**Comment by algar42** [comment] 2019-10-16 08:25
If the issue is about enabling/disabling modules at a state level, i.e. here:
![image](https://user-images.githubusercontent.com/40002726/66901367-408e0f80-f007-11e9-99d3-1293305d85dd.png)

I can confirm, in 2.0.29, once any module enabled first time, iobroker does not allow to disable them all anymore.. it wants at least one still enabled. In other words you can't disable the last one.

**Comment by MK-66** [comment] 2019-10-16 15:51
No, it's not possible for me to disable object if storage of an object was once enabled e.g. Homematic Thermostat datapoint actual_temperature, it keeps Active. (I have enabled storage of more than one object). I tested this on my Debian Buster VM Testsystem, I tried also to run installationfixer, nothing changed, also checked different Browsers Chrome, Firefox, Edge.

So therefore I downgraded my Raspi Pi 4 productiv system back to js-controller 1.15.14 and everything is ok.

Next step I will deinstall history adapter 1.8.7 or downgrade to 1.8.6 and try if the problem still occur after that.

**Comment by Apollon77** [comment] 2019-10-16 22:15
I can reproduce it now ... need to check :-(

**Comment by Apollon77** [comment] 2019-10-17 07:36
fixed in 2.0.34 on Github, later in latest

**Closed by Apollon77** 2019-10-17 07:36 UTC

**Comment by algar42** [comment] 2019-10-17 08:23
in 2.0.33 I now can switch off all the modules. 
The only one thing is that the settings icon 
![image](https://user-images.githubusercontent.com/40002726/66991324-806cf980-f0d0-11e9-8bc6-c3ff57aa1022.png)
does not get gray when everything is switched off.. 
could you please check whether it is corrected as well in 2.0.34?

**Comment by Apollon77** [comment] 2019-10-17 17:17
It worked for me
