### ISSUE TITLE
Greenlock issue - no admin from external in 1.5.8

### ISSUE THREAD

**Issue by justr1** [ioBroker/ioBroker.js-controller#372] opened 2019-05-14 04:40 UTC
After Upgrade to 1.5.8 I can't access admin at external URL (fgljpxxxxxxxxx.myfritz.net).

Working:
https://localhost:port
https://interneIP:port
https://externeIP:port

Doesn't work:
https://externeURL:port

Since the external IP is working, Port-Forwarding can't be the reason and I can access my FritzBox, so DNS is ok.

Further a downgrade to 1.5.7 doesn't change anything. I found out, that Greenlock (Let's encrypt) is the problem. js-controller 1.5.7 contains greenlock@2.6.8 and 1.5.8 contains greenlock 2.7.18. But Downgrade to 1.5.7 keeps greenlock 2.7.18. With try&error I found greenlock@2.7.1 as last working greenlock version.

So my solution:
cd <iobroker> (at my Mac "cd /usr/local/iobroker")
cd node_modules/iobroker.js-controller
npm i greenlock@2.7.1

HTH, justr

**Comment by AlCalzone** [comment] 2019-05-14 06:33
So we should just pin greenlock to 2.7.1 instead of using a version range (^ or ~) I guess.

**Comment by Apollon77** [comment] 2019-05-14 06:38
In theory ot wuld be great to find out when the problem started ... so ideally install 2.7.2 and test again, then 2.7.3 and such (or use more a "ich chose midle of the version area, so test 2.7.9 and then you know depending on result if 2.7.13 or 2.7.5 should be next and so find out which version started not working ... Then we also can report this to the greenlock devs and maybe check code 

@justr1 Just as question: would you be willing/have time to do such test to find out the exact affecting version of greenlock causing this problem?

**Comment by Apollon77** [comment] 2019-05-14 06:44
@justr1 Or do you mean that you already did tried that?

**Comment by justr1** [comment] 2019-05-14 06:45
I have already! And 2.7.1 was the last working release. The next published
version (iirc 2.7.3) doesn't work anymore.

Ingo Fischer <notifications@github.com> schrieb am Di. 14. Mai 2019 um
08:38:

**Comment by Apollon77** [comment] 2019-05-14 06:49
Cool thank you! I will try to translate this into an isue for greenlock

**Comment by Apollon77** [comment] 2019-05-14 07:02
Let's see the outcome here: https://git.coolaj86.com/coolaj86/greenlock.js/issues/38

**Comment by solderjs** [comment] 2019-05-14 08:32
I'm having trouble understanding what's going on.

What is the configuration that fails and what are the plugins being used?

The update should not have broken backwards-compatibility and if I can better understand how to test and reproduce the problem I will fix it.

**Comment by Apollon77** [comment] 2019-05-14 08:46
Thank you for your very fast reaction, We will try toget you the needed details ...

**Comment by Apollon77** [comment] 2019-05-16 21:14
@justr1 We just released an js-controller 1.5.9 which pins version 2.7.1 of greenlock. Could you please give it a try? It is on npm already

@solderjs This is just a temporary solution because we want to bring out 1.5. of js-controller very soon. We need to look deeper into this after that release in preparation of 2.0 release as next step.

**Comment by justr1** [comment] 2019-05-17 05:44
For me js-controller 1.5.9 initiates a downgrade to greenlock@2.7.1 an DynIP-Domain works again. Thanks!

**Comment by solderjs** [comment] 2019-05-17 14:54
Yes, if you can show me what the config looks like, I may be able to quickly identify the issue.

I'd say stay pinned until v3.0 comes out. It will support Draft 15 of the ACME spec, which is required for the November 2019 update, and I'll be dropping all of the old backwards-compatibility code, much of which contributes to bugs.

**Comment by Apollon77** [comment] 2019-05-17 14:57
The only occurence I found is https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/letsencrypt.js#L53 ... maybe this helps (Sorry but I'm completely not into that part of the code)

**Comment by solderjs** [comment] 2019-11-01 21:51
Greenlock v3 is out:

https://git.rootprojects.org/root/greenlock.js

I haven't got the new video tutorials up yet, but the docs are fairly decent.

`approveDomains` is gone. Instead you can use the `manage` callbacks.

**Comment by justr1** [comment] 2019-11-02 14:34
I haven't took care about the installed Greenlock version since May, but it seems that Greenlock was upgraded in between, probably with js-controller 2.0.x. Everything was working fine, until the same issue as reported here, has happened with upgrade from Greenlock 2.8.7 to 2.8.8. iirc it was a side effect of upgrading js-controller from 2.0.34 to 2.0.35. But this time a manual downgrade to greenlock 2.8.7 didn't work. Due to observing delivery of iobrokers own certificates I tried (beside a lot of other stuff) to manual define my own certificates in js-controllers system settings (path and file names in sheet "Certificates" (german: "Zertifikate")). Surprisingly it works even with new 2.8.8, although this was never necessary before. So currently all works fine with
```
└─┬ iobroker.js-controller@2.0.39
  └── greenlock@2.8.8 
```
Maybe we can close this issue, but perhaps we should explain better to define certificates in system setting manually.

Thanks guys for your hard work, justr

**Comment by solderjs** [comment] 2019-11-02 16:14
Greenlock v2.x won't work anymore.

As of Nov 1st Let's Encrypt changed their API:

https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380

There's a grace period for production sites, but all tests will fail.

All of the prior bugs have been fixed in v3 and the API has been greatly simplified. I'm still taking feedback and adjusting APIs in an _additive_ way, but the API is locked tight in terms of backwards compatibility. All of the nasty legacy code that caused bugs is gone (it's been rewritten from scratch).

I'm still scrambling to update all of the docs.

**Comment by foxriver76** [comment] 2021-01-07 21:23
shoul be fixed with new greenlock version? @Apollon77

**Comment by Apollon77** [comment] 2021-01-07 21:25
exactly, i would close here

**Closed by Apollon77** 2021-01-07 21:25 UTC
Labels: bug
