### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.js-controller#116] opened 2016-08-27 09:25 UTC
Since a few js-controller versions I am getting the following error message if I do a `sudo iobroker update` on the command-line to check for any new adapter versions:

```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
```

I am using  0.11.3 of js-controller here.

**Comment by GermanBluefox** [comment] 2016-08-28 07:55
What the version of node.js, OS and platform (Raspi, PC, OSX, ...)?

**Comment by jens-maus** [comment] 2016-08-28 08:02
Node.js has version 4.5.0, os is ubuntu linux 16.04 and the hardware is a intel nuc system

**Comment by GermanBluefox** [comment] 2016-09-01 21:32
I cannot reproduce the problem on Windows PC and 4.5.0 node.js.
Will try to get Ubuntu. 
Perhaps, the problem on some installed adapters. Please try to upgrade every own adapter apart and try to detect, when the "iobroker upgrade" command will normal work,

**Comment by GermanBluefox** [comment] 2016-09-08 19:26
There is a new version 0.12.3 on github with fix

**Comment by hielfx** [comment] 2016-09-13 14:19
I am having the same issue on Windows 10, same node version

**Comment by GermanBluefox** [comment] 2016-10-02 20:30
> I am having the same issue on Windows 10, same node version

But which controller version?

**Comment by GermanBluefox** [comment] 2016-11-08 22:00
With 0.13.x it must be fixed.

**Comment by GermanBluefox** [comment] 2016-11-18 08:34
I close this, because fixed.

**Closed by GermanBluefox** 2016-11-18 08:34 UTC
