### ISSUE TITLE
ghost alias datapoints 

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.js-controller#519] opened 2019-10-31 17:34 UTC
if an alias is added to alias.0 and the assigned dp will be deleted - the alias is still available in eg. vis or the object tab in the admin but it is like a ghost in the system - if you scan the alias.0 with a selector - it  will not be found

more detailed info in the forum:
https://forum.iobroker.net/post/319210

**Comment by algar42** [comment] 2019-10-31 18:43
when manually added to alias we need to restart iobroker to make states from alias.0 avaialable in selectors and scripts. 
Is there a way to automatically scan for added objects/states?

**Comment by Apollon77** [comment] 2019-11-04 22:02
Ok, some general infos (because I still try to "get" the problem of this topic)
1. For alias only Objects really exists. These objects point to the "target object id" for which this alias is "linked"
2. As soon as a "setState" for the alias object is made, it gets converted to a setState for the target object which is then really set. No state value is really stored for the alias!
3. When an adapter subscribes to an alias then the adapter code is looking up the target and in reality subscribed to the target, but remembers the mapped alias.
4. With a setState for the targetObject (directly or indirectly via 2.) the state value is really set and also published to all subscribed adapters
5. As soon as a state update is received for a state it is send to the adapter directly and also with their stored mapped alias value

Adapters like Javascript that cache states and objects may have an issue here because the alias mapping is kind of completely transparent to them.

@GermanBluefox I think we need to adapt https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L4741 because with the current code a "state removal aka null" is not sent for the alias ids to the adapter, so for adapter the state stays on last value. what about only doing formatValue when not state===null and handle error in formatting somehow?

With this it should work again, or ?!

**Comment by AlCalzone** [comment] 2019-11-05 07:10
I think what @algar42 means is that the javascript adapter seems to ignore objects that were created while the adapter is already running. This is because the selector cache is not updated when objects are created:
https://github.com/ioBroker/ioBroker.javascript/issues/109

**Comment by algar42** [comment] 2019-11-05 07:40
yes, exactly!

**Comment by Apollon77** [comment] 2019-11-05 07:54
Please check the newest Javascript adapters (4.3.0+) because there were fixes exactly for that in

**Comment by algar42** [comment] 2019-11-05 08:20
I have js adapter 4.3.2 currently installed and it seems to me that it still does not work correctly. 
Here is what I just tried to do:
1. Manually create state in alias.0 namespace:
![image](https://user-images.githubusercontent.com/40002726/68190053-c1fd1000-ffbd-11e9-95b6-e988a8cf4ca2.png)
2. Add target alias id:
![image](https://user-images.githubusercontent.com/40002726/68190083-d17c5900-ffbd-11e9-8cdf-b538662ba424.png)
3. Create simple script that subscribes to created state:
![image](https://user-images.githubusercontent.com/40002726/68190170-f7a1f900-ffbd-11e9-8897-e4958c6d81cc.png)
4. Try to change states value... and there is no expected log message, whereas it says that state is subscribed:
![image](https://user-images.githubusercontent.com/40002726/68190246-12746d80-ffbe-11e9-9eb6-a75794bdee2d.png)

The expected log message appears in the log only after restart of JS adapter:
![image](https://user-images.githubusercontent.com/40002726/68190325-3d5ec180-ffbe-11e9-9ea5-8795299d0170.png)

**Comment by GermanBluefox** [comment] 2019-11-07 13:13
Please test 4.3.3

**Comment by Apollon77** [comment] 2019-11-07 14:29
@GermanBluefox was this really in 4.3.3? Or is this comment on wrong ticket? (4.3.3 is search optimizations, or ?!)

**Comment by algar42** [comment] 2019-11-07 15:34
> Please test 4.3.3

Nothing changed. Absolutely the same thing as above.

**Comment by Apollon77** [comment] 2019-11-07 15:52
In fact we are mixing up two things in that issue!!

1.) the original post was about deleted states and aliases
2.) @algar42 added "i need to restart iobroker when subscribing to new alas states".

Correct?

First shoud be fixed in some days with controller 2.0.40

@algar42 Because noone states: which js-controller version you use? If not 2.0.39 then update first and retry please

**Comment by liv-in-sky** [comment] 2019-11-07 15:55
I need a little bit more time - I will check with 4.3.3  - and come back to you

**Comment by algar42** [comment] 2019-11-07 15:57
@Apollon77 yes I'm on 2.0.39.

**Comment by AlCalzone** [comment] 2019-11-07 16:10
Is it really necessary to restart iobroker to get the aliases to work? Or is the JS Adapter enough?

**Comment by liv-in-sky** [comment] 2019-11-07 16:33
sorry - I'm a little bit confused  - because of this I answer to my first question:
please keep in mind - I try to write a scipt which should detect all defined aliases and should check wether the assigned datapoint is still in the system

I did an update to JS4.3.3. - controller is  2.0.39

I have added the alias under alias.0 - I defined a wrong assignment to a datapoint which is not existing - I run  a script with selektor over alias.0 and got back what  I want - the alias is there and the assignment is wrong because the assigned dp s not existing

then  I did  : iobroker restart

now the script runs again and the selector can't find the created alias-object with the false assigned dp - I can see the alias object in the object-tab but the selector won't find this object

commandi in script:
![Image 8](https://user-images.githubusercontent.com/18462890/68407379-beb38100-0183-11ea-8cd7-586228e4ab34.png)
log: should be 4 aliases !!!
![Image 7](https://user-images.githubusercontent.com/18462890/68407396-c8d57f80-0183-11ea-9ac6-6a696eed5219.png)
object tab: here you can see 4 objects !!
![Image 9](https://user-images.githubusercontent.com/18462890/68407424-d5f26e80-0183-11ea-87f7-57dcf926081c.png)

raw of alias - BADALL1 is not existing as a datapoint
![Image 10](https://user-images.githubusercontent.com/18462890/68407452-e276c700-0183-11ea-98db-8dc242d8e7dd.png)

**Comment by Apollon77** [comment] 2019-11-07 19:12
Ok ... when i understand it then using the selector the way you do is misleading. It checks for states existing in the JavaScript states cache. Not objects!

When you now read my Infos above then you see that alias states do not really exist. So also JavaScript when staring is not getting any value for them. As soon as you set the target or alias state the alias state receives a value. This is then stored in the JavaScript adapter state cache and after that you get it. 

So in fact you need to use the selector and select explicitly objects and not states. Would need to check how this works. 

But with this the issues here would be „as designed“

**Comment by Apollon77** [comment] 2019-11-07 19:13
Ps: the reason why you see the object in JavaScript directly after creation may be that it gets a default value or such and so a alias state value „appears“

**Comment by Apollon77** [comment] 2019-11-15 15:14
Clarified? Then I close here

**Closed by Apollon77** 2019-11-15 15:14 UTC
Labels: bug
